query CheckItem($shopperId: String!, $productId: String!, $sku: String) {
  checkList(shopperId: $shopperId, productId: $productId, sku: $sku)
    @context(provider: "vtex.wish-list"){
    inList
    listNames
    listIds
    message
  }
}
